# Generated by Django 3.0.7 on 2020-06-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20200611_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_cancelled',
            field=models.BooleanField(blank=True, default=False, verbose_name='Cancelled?'),
        ),
    ]
