# Generated by Django 3.0.7 on 2020-06-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_event_is_cancelled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={},
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='name',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='slug',
        ),
        migrations.AddField(
            model_name='calendar',
            name='Nom',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='Prenom',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
