# Generated by Django 3.0.7 on 2020-06-17 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20200616_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='Nom',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='Prenom',
            new_name='prenom',
        ),
        migrations.AddField(
            model_name='calendar',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
